api_platform:
    title: Hello API Platform
    version: 1.0.0
    enable_docs: true  # Ensure documentation is enabled
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    